---
title: Let's Talk Payments
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: LTP website
author: prasad
logo: "/uploads/ltplogo.png"
github: 
about: Web developer
baseurl: 
url: 
allowsearch: true
disqus_shortname: prasad
google_analytics: 
share:
  twitter_username: "\\#"
  fb_appid: 
enableTags: true
paginate: 2
per_page: 2
paginate_path: "/page:num/"
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-gist
