# Site Settings
title: Let's Talk Payments
email: prasad@letstalkpayments.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/medici"
url: "http://prasadltp.github.io"
permalink: /:year/:month/:day/:title
twitter_username: nnvdprasad
github_username:  prasadltp
# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
