# Site Settings
title: Let's Talk Payments
email: prasad@letstalkpayments.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/medici"
url: "http://prasadltp.github.io"
twitter_username: nnvdprasad
github_username:  prasadltp
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
