title: Lets Talk Payments - zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
description: My Personal Blog
author: prasad
logo: 
github: 
about: Freelance developer

baseurl: '/medici'
url: ""

allowsearch: true

disqus_shortname: prasad
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
