title: Let's Talk Payments
description: LTP website
author: prasad
logo: 
github: 
about: Web developer

baseurl: '/medici'
url: ""

allowsearch: true

disqus_shortname: prasad
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
